### ISSUE TITLE
ボタンのフォントが細い、テキスト位置がずれている

### ISSUE THREAD

**Issue by kota-yata** [codeforjapan/CivicTechCC-Website#6]
![image](https://user-images.githubusercontent.com/51294895/87509489-9d107f00-c6ac-11ea-8602-401a553222d3.jpeg)

「エントリーする」が中央に来ているので「エントリーする」と「8月31日まで！」をdivで囲んで中央に寄せれば違和感はなくかるはず。

**Comment by MaySoMusician** [comment]
これ、検証環境とブラウザは何ですか？（WindowsのChromeだと問題無かった気が...）

**Comment by NEKOYASAN** [comment]
![image](https://user-images.githubusercontent.com/17000370/87557140-8260f900-c6f2-11ea-85b1-5bb3673a18eb.png)
一応こうしてたはずなんですが...

**Comment by kota-yata** [comment]
iOSの基本的なブラウザ全てですね(Chrome, Safari, Edge, Firefox)。ヘッダーのエントリーボタンは問題ないんですがページ内のエントリーのボタンがスクショのような状態になっています

**Comment by NEKOYASAN** [comment]
Webkit系統だとMacだとどうです？

**Comment by kota-yata** [comment]
Safari, Chrome, Firefoxで見てみましたがMacでは正常に表示されてます

**Comment by MaySoMusician** [comment]
これ、今も直ってない感じかな（iOSデバイス持ってないのでわからん）

**Comment by kota-yata** [comment]
なぜか直りました。。。単純に僕の端末の問題だった可能性もあるが

**Comment by MaySoMusician** [comment]
再発したらまた考えるということで
