### ISSUE TITLE
スケジュールの箇条書きの丸印と文章の差が大きい

### ISSUE THREAD

**Issue by kota-yata** [codeforjapan/CivicTechCC-Website#8]
![image](https://user-images.githubusercontent.com/51294895/87510114-ef05d480-c6ad-11ea-93e9-1865022fd496.jpeg)

liタグのCSSを変更すれば解決のはず

**Comment by MaySoMusician** [comment]
そもそもビュレット（「•」のこと）無くても良いかも？

**Comment by kota-yata** [comment]
そうすると日本語タイトルとフォントサイズが一緒なのであまり良い感じではないですね。
ビュレットは残しておきたいです
